### PR TITLE
fix: make `Optional`s always nullable

### LINKED ISSUE #718: Under NonNullApi, Optionals aren't nullable
### Description of the bug 
When I use `@NonNullApi` on the package containing my endpoint, I still expect `Optional<T>` return types to be nullable.

Consider this method signature:
```java
public Optional<String> sayHello(String name) { ... }
```
The generated return type will be `Promise<string | undefined>`, but if I add the `@NonNullApi` package-level annotation, it becomes `Promise<string>`.

This happens with both generators. I'm using version `2.0.0.alpha8`.

### PR DESCRIPTION
**Pull request by cromoteca**
Fixes #718

### CODE REVIEW

File: packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java [hunk 1]
```diff
@@ -51,29 +52,35 @@ public void enter(NodePath<?> nodePath) {
...
-        // Apply annotations from package (NonNullApi)
-        var annotations = getPackageAnnotationsStream(nodePath);
-
-        // Apply from current node, if source is annotated
-        if (nodePath.getNode().getSource() instanceof AnnotatedModel) {
-            annotations = Stream.concat(annotations,
-                    ((AnnotatedModel) nodePath.getNode().getSource())
-                            .getAnnotationsStream());
+        var node = nodePath.getNode();
+        if (node.getTarget()instanceof Schema schema) {
```
Comment (cromoteca) [inline packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java:56]: There is a formatting rule concerning `instanceof` that is not working correctly or is just wrong.

Comment (Lodin) [inline packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java:56]: Hmm, as far as I know, we cannot use that syntax in the production code yet since we need to support Java 11.
```suggestion
        if (node.getTarget() instanceof Schema) {
          var schema = node.getTarget();
```

File: packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java [hunk 2]
```diff
@@ -51,29 +52,35 @@ public void enter(NodePath<?> nodePath) {
...
+            if (((SpecializedModel) node.getSource()).isOptional()) {
```
Comment (Lodin) [inline packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java:57]: Are we sure we have a `SpecializedModel` here?

**Review by Lodin — CHANGES_REQUESTED** [review]

File: packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java (hunk 1 above)
Comment (cromoteca) [reply packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java:56]: Are we going to cherry-pick to old releases?

Comment (Lodin) [reply packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java:56]: Hmm, I'm confused 😅 @platosha, what would you say?

**Review by Lodin — APPROVED** [review]

**Review by platosha — APPROVED** [review]
