### PR TITLE
chore: fix java doc

### LINKED ISSUE #3000: Outdated Javadoc on EndpointInvoker constructor
The Javadoc for `EndpointInvoker` constructor mentions `endpointObjectMapper` as a `optional factory bean to override the default ...`, but the argument is actually an `ObjectMapper`, not a factory.
Most likely a left-over from recent refactoring.

https://github.com/vaadin/hilla/blob/25417fcbc03b9b263db8b60c753b7fae6a6cc30f/packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointInvoker.java#L85-L90

### PR DESCRIPTION
**Pull request by taefi**
Fixes #3000

### CODE REVIEW

File: packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointInvoker.java [hunk 1]
```diff
@@ -83,9 +83,8 @@ public class EndpointInvoker {
      * @param applicationContext
      *            The Spring application context
      * @param endpointObjectMapper
-     *            optional factory bean to override the default
-     *            {@link JacksonObjectMapperFactory} that is used for
-     *            serializing and deserializing request and response bodies Use
+     *            The object mapper to be used for serialization and
+     *            deserialization of request and response bodies. Use the
      *            {@link EndpointController#ENDPOINT_MAPPER_FACTORY_BEAN_QUALIFIER}
      *            qualifier to override the mapper.
```
Comment (mcollovati) [inline packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointInvoker.java:89]: I would clarify a little bit the override hint, since the qualifier is not supposed to be put on mapper bean, but on a factory. Maybe something like


> To override the mapper, use the {@link EndpointController#ENDPOINT_MAPPER_FACTORY_BEAN_QUALIFIER} qualifier on a JacksonObjectMapperFactory bean definition.

**Review by mcollovati — APPROVED** [review]
