### PR TITLE
fix: ignore absence of file-routes.json at startup in dev mode

### LINKED ISSUE #2408: file-routes.json cannot be found
### Describe the bug

Each Vaadin 24.4 application, that contains Hilla, shows this exception on startup, complaining about `file-routes.json` file not found:
```
java.io.FileNotFoundException: .../skeleton-starter-flow-spring/./src/main/frontend/generated/file-routes.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method) ~[na:na]
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216) ~[na:na]
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157) ~[na:na]
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111) ~[na:na]
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86) ~[na:na]
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189) ~[na:na]
	at java.base/java.net.URL.openStream(URL.java:1161) ~[na:na]
	at com.vaadin.hilla.route.ClientRouteRegistry.registerClientRoutes(ClientRouteRegistry.java:158) ~[hilla-endpoint-24.4-20240506.022159-195.jar:na]
	at com.vaadin.hilla.startup.RouteUnifyingServiceInitListener.serviceInit(RouteUnifyingServiceInitListener.java:101) ~[hilla-endpoint-24.4-20240506.022159-195.jar:na]
```

This, however, doesn't affect the application behaviour and most likely an intermediate state during the build, when this file isn't created yet.

Related-to https://github.com/vaadin/hilla/issues/2358#issuecomment-2079454615, as a possible way to fix it, this exception can be ignored in the `ClientRouteRegistry`.

### Expected-behavior

No exception

### Reproduction

Any Hilla or Flow+Spring-Boot starter for Vaadin 24.4.

### System Info

Vaadin 24.4.0.beta2

### PR DESCRIPTION
**Pull request by taefi**
## Description

Fixes #2408

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java [hunk 1]
```diff
@@ -165,8 +165,16 @@ public synchronized void registerClientRoutes(
                 this.lastUpdated = lastUpdated;
             }
         } catch (IOException e) {
-            LOGGER.warn("Failed load {} from {}", FILE_ROUTES_JSON_NAME,
-                    viewsJsonAsResource.getPath(), e);
+            if (deploymentConfiguration.isProductionMode()) {
+                // The file should be available in production mode:
+                LOGGER.warn("Failed to load {} from {}", FILE_ROUTES_JSON_NAME,
```
Comment (Artur-) [inline packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java:170]: So it should be an error?

File: packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java [hunk 2]
```diff
@@ -190,16 +198,21 @@ public synchronized void loadLatestDevModeFileRoutesJsonIfNeeded(
...
         var isProductionMode = deploymentConfiguration.isProductionMode();
         if (isProductionMode) {
             return getClass().getResource(FILE_ROUTES_JSON_PROD_PATH);
         }
         try {
-            return deploymentConfiguration.getFrontendFolder().toPath()
-                    .resolve("generated").resolve(FILE_ROUTES_JSON_NAME).toUri()
-                    .toURL();
+            var fileRoutesJson = deploymentConfiguration.getFrontendFolder()
+                    .toPath().resolve("generated")
```
Comment (Artur-) [inline packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java:209]: FrontendUtils. getFrontendGeneratedFolder ?

File: packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java [hunk 3]
```diff
@@ -144,18 +145,18 @@ private String removeTrailingSlash(String path) {
...
             DeploymentConfiguration deploymentConfiguration,
             LocalDateTime lastUpdated) {
-        var viewsJsonAsResource = getViewsJsonAsResource(
+        var fileRoutesJsonAsResource = getFileRoutesJsonAsResource(
                 deploymentConfiguration);
-        if (viewsJsonAsResource == null) {
+        if (fileRoutesJsonAsResource == null) {
             LOGGER.debug(
-                    "No {} found under {} directory. Skipping client route registration.",
+                    "No {} found under {} directory yet. Skipping client route registration.",
```
Comment (Artur-) [inline packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java:152]: It is weird to put "yet" in the error message when you are not sure it will ever be found.

Comment (Artur-) [reply packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java:152]:
```suggestion
                    "No {} found under {} directory. Skipping client route registration.",
```

**Review by Artur- — DISMISSED** [review]

**Review by ZheSun88 — APPROVED** [review]
