### PR TITLE
fix(file-router): avoid errors and full reloads from Vite HMR when a route is added or removed

### LINKED ISSUE #2552: Errors when removing a route
### Describe the bug

When you remove a route, you see
image

and then the page reloads

### Expected-behavior

There are no errors and the page is not reloaded

### Reproduction

`npm init vaadin`

Choose Hilla views

`mvn`

`rm src/main/frontend/views/about-hilla.tsx` after the app is open

### System Info

Vaadin 24.4.2

### PR DESCRIPTION
**Pull request by platosha**
Fixes #2552

### CODE REVIEW

File: packages/ts/file-router/src/vite-plugin.ts [hunk 1]
```diff
@@ -83,40 +87,80 @@
...
 
-        generateRuntimeFiles(_viewsDir, runtimeUrls, extensions, _logger, debug).catch((e: unknown) =>
-          _logger.error(String(e)),
+      // Check and update file routes if needed.
+      if (await _generateRuntimeFiles()) {
+        // The "file-routes.ts" file was changed at this point, so it should
+        // be considered within the HMR update that caused the routes update.
+
+        const mg = this.environment.moduleGraph;
+        const fileRoutesModules = mg.getModulesByFile(fileURLToPath(runtimeUrls.code).replaceAll('\\', '/'))!;
```
Comment (Lodin) [inline packages/ts/file-router/src/vite-plugin.ts:131]: You ca

File: packages/ts/file-router/src/vite-plugin.ts [hunk 2]
```diff
@@ -83,40 +87,80 @@ export default function vitePluginFileSystemRouter({
...
```
Comment (Lodin) [inline packages/ts/file-router/src/vite-plugin.ts:131]:
```suggestion
        const fileRoutesModules = mg.getModulesByFile(fileURLToPath(runtimeUrls.code, { windows: false }))!;
```

File: packages/ts/file-router/src/vite-plugin.ts [hunk 3]
```diff
@@ -83,40 +87,80 @@ export default function vitePluginFileSystemRouter({
...
+
+        // Make eager update for file routes in Vite module graph
+        // for consistency with the generated file contents.
+        await Promise.all(
+          [...fileRoutesModules].map(async (fileRouteModule) => {
```
Comment (Lodin) [inline packages/ts/file-router/src/vite-plugin.ts:136]:
```suggestion
          Array.from(fileRoutesModules, async (fileRouteModule) => {
```

File: packages/ts/file-router/src/vite-plugin.ts [hunk 4]
```diff
@@ -62,14 +62,18 @@ export default function vitePluginFileSystemRouter({
...
 
   return {
     name: 'vite-plugin-file-router',
+    enforce: 'pre',
     configResolved({ logger, root, build: { outDir } }) {
       const _root = pathToFileURL(root);
       const _generatedDir = new URL(generatedDir, _root);
 
       _viewsDir = new URL(viewsDir, _root);
+      _viewsDirUsingSlashes = fileURLToPath(_viewsDir, {}).replaceAll('\\', '/');
```
Comment (Lodin) [inline packages/ts/file-router/src/vite-plugin.ts:76]:
```suggestion
      _viewsDirPosix = fileURLToPath(_viewsDir, { windows: false });
```

File: packages/ts/file-router/src/vite-plugin.ts [hunk 5]
```diff
@@ -62,14 +62,18 @@ export default function vitePluginFileSystemRouter({
   let _outDir: URL;
   let _logger: Logger;
   let runtimeUrls: RuntimeFileUrls;
+  let _generateRuntimeFiles: () => Promise<boolean>;
+  let _viewsDirUsingSlashes: string;
```
Comment (Lodin) [inline packages/ts/file-router/src/vite-plugin.ts:66]:
```suggestion
  let _viewsDirPosix: string;
```

File: packages/ts/file-router/test/vite-plugin/vite-plugin.spec.ts [hunk 6]
```diff
@@ -35,54 +96,147 @@ describe('@vaadin/hilla-file-router', () => {
...
-      expect(mockServer.hot.send).to.not.be.called;
-      mockServer.watcher.emit('change', fileURLToPath(new URL('file.tsx', viewsDir)));
-      expect(mockServer.hot.send).to.not.be.called;
+    it('should not send updates for file-routes.ts separately', async () => {
+      expect(mockEnvironment.hot.send).to.not.be.called;
+      const modulesToUpdate = await hotUpdate({ type: 'update', file: fileRoutesTsPath });
+      // Updates to file-routes.ts are not processed separately, instead they
+      // are combined with the update of the triggering file.
+      expect(mockEnvironment.hot.send).to.not.be.called;
+      expect(modulesToUpdate).to.be.deep.equal([]);
```
Comment (Lodin) [inline packages/ts/file-router/test/vite-plugin/vite-plugin.spec.ts:160]:
```suggestion
      expect(modulesToUpdate).to.be.an('array').that.is.empty;
```

File: packages/ts/file-router/test/vite-plugin/vite-plugin.spec.ts [hunk 7]
```diff
@@ -35,54 +96,147 @@ describe('@vaadin/hilla-file-router', () => {
...
+      expect(mockEnvironment.hot.send).to.not.be.called;
+      const viewFilePath = fileURLToPath(new URL('file.tsx', viewsDir));
+      const viewFileModule = createMockEnvironmentModuleNode(viewFilePath);
+      viewFileModule.importers.add(fileRoutesModule);
+      const modulesToUpdate = await hotUpdate({ type: 'create', file: viewFilePath, modules: [viewFileModule] });
+      expect(mockEnvironment.fetchModule).to.be.calledWith(fileRoutesTsPath);
+      // HMR for routes and view file together.
+      expect(modulesToUpdate).to.not.equal(undefined);
+      expect(modulesToUpdate!.length).to.equal(2);
+      expect(modulesToUpdate![0]).to.eq(fileRoutesModule);
```
Comment (Lodin) [inline packages/ts/file-router/test/vite-plugin/vite-plugin.spec.ts:188]: Let's not use that weird `chai`'s aliases 😓 I'm always confused about what they mean. If it is a deep equality, let's have `to.be.deep.equal()`, otherwise `to.be.equal`.

File: packages/ts/file-router/test/vite-plugin/vite-plugin.spec.ts [hunk 8]
```diff
@@ -35,54 +96,147 @@ describe('@vaadin/hilla-file-router', () => {
...
+    });
+
+    it('should send hot reload for only file routes when a view file not imported anywhere is removed', async () => {
+      expect(mockEnvironment.hot.send).to.not.be.called;
+      const viewFilePath = fileURLToPath(new URL('file.tsx', viewsDir));
+      const viewFileModule = createMockEnvironmentModuleNode(viewFilePath);
+      const modulesToUpdate = await hotUpdate({ type: 'delete', file: viewFilePath, modules: [viewFileModule] });
+      expect(mockEnvironment.fetchModule).to.be.calledWith(fileRoutesTsPath);
+      // HMR for only file routes.
+      expect(modulesToUpdate).to.not.equal(undefined);
```
Comment (Lodin) [inline packages/ts/file-router/test/vite-plugin/vite-plugin.spec.ts:213]: Here and in other places:
```suggestion
      expect(modulesToUpdate).to.not.be.undefined;
```

File: packages/ts/file-router/test/vite-plugin/vite-plugin.spec.ts
Comment (Lodin) [inline packages/ts/file-router/test/vite-plugin/vite-plugin.spec.ts:1]: Since SonarCloud is upset about repeating code, I'd suggest to either put the repeated part into a separate `describe` block with custom `beforeEach`, or to put the repeating code into a function.

File: packages/ts/file-router/test/vite-plugin/vite-plugin.spec.ts [hunk 9]
```diff
@@ -35,54 +96,147 @@ describe('@vaadin/hilla-file-router', () => {
...
+    it('should send hot reload for only file routes when a view file not imported anywhere changes', async () => {
+      expect(mockEnvironment.hot.send).to.not.be.called;
+      const viewFilePath = fileURLToPath(new URL('file.tsx', viewsDir));
+      const viewFileModule = createMockEnvironmentModuleNode(viewFilePath);
+      const modulesToUpdate = await hotUpdate({ type: 'update', file: viewFilePath, modules: [viewFileModule] });
+      expect(mockEnvironment.fetchModule).to.be.calledWith(fileRoutesTsPath);
+      // HMR for only file routes.
+      expect(modulesToUpdate).to.not.equal(undefined);
+      expect(modulesToUpdate!.length).to.equal(1);
+      expect(modulesToUpdate![0]).to.eq(fileRoutesModule);
```
Comment (Lodin) [inline packages/ts/file-router/test/vite-plugin/vite-plugin.spec.ts:202]:
```suggestion
      expect(modulesToUpdate).to.be.deep.equal([fileRoutesModule]);
```

**Review by Lodin — CHANGES_REQUESTED** [review]
Overall, PR looks good. I have only a couple of stylistic changes

File: packages/ts/file-router/src/vite-plugin.ts (hunk 2 above)
Comment (platosha) [reply packages/ts/file-router/src/vite-plugin.ts:131]: `windows` option is Node 22+. Since Vaadin still supports Node 20, let us not use it just yet.

**Review by Lodin — APPROVED** [review]
