### PR TITLE
fix(parser): support type parameter and argument annotations

### LINKED ISSUE #604: hillaEngine: Basic types other than String are always nullable in Kotlin
### Description of the bug 
image

### Actual behavior
image

### Versions:
Hilla: 23.2.4
Flow: 23.2.4
Java: JetBrains s.r.o. 17.0.4.1
OS: amd64 Windows 10 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Live reload: Java active (HotswapAgent): Front end active

### PR DESCRIPTION
**Pull request by platosha**
Fixes #604

### CODE REVIEW

File: packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/TypeArgumentSourceModel.java [hunk 1]
```diff
@@ -37,4 +50,17 @@ protected List<SignatureModel> prepareAssociatedTypes() {
...
+    private Stream<AnnotationInfoModel> getWildcardAnnotationsStream() {
+        // FIXME: workaround for
+        // https://github.com/classgraph/classgraph/issues/741,
+        // remove when the issue is fixed.
+        if (getWildcard().equals(TypeArgument.Wildcard.NONE)) {
+            return Stream.empty();
+        }
+        var strings = List.of(origin.toString().split(" "));
+        strings = strings.subList(0, strings.indexOf("?"));
+        return AnnotationInfoArtificialModel
```
Comment (Lodin) [inline packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/TypeArgumentSourceModel.java:63]: Just to be more consistent here
```suggestion
        return AnnotationInfoModel
```

File: packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/TypeParameterSourceModel.java [hunk 2]
```diff
@@ -40,4 +41,13 @@ protected List<SignatureModel> prepareBounds() {
                 .filter(Objects::nonNull).map(SignatureModel::of).distinct()
                 .collect(Collectors.toList());
     }
+
+    private Stream<AnnotationInfoModel> getParameterAnnotationsStream() {
+        // FIXME: workaround for
+        // https://github.com/classgraph/classgraph/issues/741,
+        // remove when the issue is fixed.
+        var strings = List.of(origin.toString().split(" "));
```
Comment (Lodin) [inline packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/TypeParameterSourceModel.java:49]: Wouldn't it break if the annotation has parameters?

**Review by Lodin — CHANGES_REQUESTED** [review]
