### PR TITLE
fix: change window and document DOM access to self checks for SW context

### LINKED ISSUE #2867: PWA endpoint errors while called from SW
### Describe the bug

Some issues stop endpoints from being called from the Service Worker. 
Most of the issues are that `window` or `document` references are not available in the worker context. 
Which should be quite easy to solve: 

- https://github.com/vaadin/hilla/blob/c7d4707995f2235574f48d84a8619ab038beb503/packages/ts/frontend/src/Connect.ts#L21
- https://github.com/vaadin/hilla/blob/c7d4707995f2235574f48d84a8619ab038beb503/packages/ts/frontend/src/Connect.ts#L303
- https://github.com/vaadin/hilla/blob/c7d4707995f2235574f48d84a8619ab038beb503/packages/ts/frontend/src/CookieManager.ts#L8

Then there are related to the same issue but more complicated issues:
1. `__REGISTER__()` includes references to `window` - but is defined in a different place    
https://github.com/vaadin/hilla/blob/c7d4707995f2235574f48d84a8619ab038beb503/packages/ts/frontend/src/index.ts#L8C1-L8C16
2. `ConnectionState` and `ConnectionIndicator `from `@vaadin/common-frontend` also have references to `window` and need to be either fixed in their repo or clone+fixed in hilla separately
https://github.com/vaadin/hilla/blob/c7d4707995f2235574f48d84a8619ab038beb503/packages/ts/frontend/src/Connect.ts#L2

3. Lastly there is an issue with atmosphere.js and default exports to Vite. Atmosphere dependency could be excluded by SW Vite plugin or by finding a better fix for exclusion as I am not sure about this approach. 

> RollupError: node_modules/@vaadin/hilla-frontend/FluxConnection.js (1:7): "default" is not exported by "node_modules/atmosphere.js/lib/browser.js", imported by "node_modules/@vaadin/hilla-frontend/FluxConnection.js".
>     at getRollupError (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
>     at error (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:392:42)
>     at Module.error (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:13858:16)
>     at Module.traceVariable (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:14306:29)
>     at ModuleScope.findVariable (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:11984:39)
>     at ChildScope.findVariable (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
>     at ClassBodyScope.findVariable (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
>     at ChildScope.findVariable (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
>     at ChildScope.findVariable (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
>     at FunctionScope.findVariable (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:7432:38)

Missing CSRF token in calling endpoints is separated in an another issue: #2791

### Expected-behavior

All DOM `window` or `document` references should be prefixed with `self.window && window...` or `self.document && document...` (or some alternative) so that SW could run without encountering them.

### Reproduction

[sw-app.zip](https://github.com/user-attachments/files/17504344/sw-app.zip)

### System Info

Hilla 24.5

### PR DESCRIPTION
**Pull request by krissvaa**
Fixes #2867

### CODE REVIEW

File: packages/ts/frontend/src/Connect.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ import {
 } from './FluxConnection.js';
 import type { VaadinWindow } from './types.js';
 
-const $wnd = window as VaadinWindow;
+const $wnd = self as VaadinWindow;
```
Comment (Lodin) [inline packages/ts/frontend/src/Connect.ts:19]: I'd suggest using `globalThis` across the code. It's guaranteed to work in any environment

**Review by Lodin — CHANGES_REQUESTED** [review]

**Review by platosha — APPROVED** [review]
