### PR TITLE
fix(file-router): improve the speed of the HMR injection

### LINKED ISSUE #2410: FS router plugin takes 30s to process a ~600 line tsx file
### Describe the bug

Both initial load of a view and making a HMR change takes 30s. On a M1 mac

### Expected-behavior

It takes around 0s.

### Reproduction

```
import * as fs from 'fs';

const hmrInjectionPattern = /(?<=import\.meta\.hot\.accept[\s\S]+)if\s\(!nextExports\)\s+return;/u;

let modifiedCode = fs.readFileSync("in2.js", {encoding: "utf-8"});

            modifiedCode = modifiedCode.replace(
                hmrInjectionPattern,
                `if (!nextExports) return;
                if (Object.keys(nextExports).length === 2 && 'default' in nextExports && 'config' in nextExports) {
                    nextExports = { ...nextExports, config: currentExports.config };
                }`
            );

console.log(modifiedCode);
```
with https://gist.github.com/Artur-/c21cf4a1961b1046e43cc4d33e2ac023 as `in2.js`
```
node go.js  33.52s user 0.04s system 99% cpu 33.868 total
```

### System Info

24.4 beta2

### PR DESCRIPTION
**Pull request by Lodin**
Fixes #2410.

It looks like the lookbehind feature in `RegExp` is extremely slow. I replaced it with the regular `RegExp`, and according to my measurements, it is almost instant.

### CODE REVIEW

File: packages/ts/file-router/src/vite-plugin.ts [hunk 1]
```diff
@@ -116,13 +117,12 @@ export default function vitePluginFileSystemRouter({
...
-            hmrInjectionPattern,
-            `if (!nextExports) return;
-            if (Object.keys(nextExports).length === 2 && 'default' in nextExports && 'config' in nextExports) {
-              nextExports = { ...nextExports, config: currentExports.config };
-            }`,
-          );
+          const injectionPattern = /import\.meta\.hot\.accept[\s\S]if\s\(!nextExports\)\s+return;/gu;
+          injectionPattern.test(modifiedCode);
+
+          modifiedCode = `${modifiedCode.substring(0, injectionPattern.lastIndex)}${INJECTION}${modifiedCode.substring(
```
Comment (Artur-) [inline packages/ts/file-router/src/vite-plugin.ts:123]: Testing this in the actual project results in `injectionPattern.lastIndex` being empty, the file being rewritten to
```
import {createHotContext as __vite__createHotContext} from "/VAADIN/@vite/client";
import.meta.hot = __vite__createHotContext("/views/@index.tsx");
if (Object.keys(nextExports).length === 2 && 'default'in nextExports && 'config'in nextExports) {
    nextExports = {
        ...nextExports,
        config: currentExports.config
    };
}
```
and failing runtime with
```
Uncaught ReferenceError: nextExports is not defined
```

Comment (Artur-) [reply packages/ts/file-router/src/vite-plugin.ts:123]: But if I add a `*` after `[\s\S], then it works and is fast

Comment (Lodin) [reply packages/ts/file-router/src/vite-plugin.ts:123]: Oops, sorry, silly mistake 😓

**Review by Artur- — APPROVED** [review]
